package org.firstinspires.ftc.teamcode.config.autoUtil.Enums;

public enum AutoStates {
    ACQUIRE_MOTIF,
    WAIT,
    GO_TO_PICKUP,
    COMPLETE_PICKUP,
    GO_TO_RELEASE,
    COMPLETE_RELEASE,
    RELEASE_WAIT,
    GO_TO_SHOOT,
    COMPLETE_SHOOT,
    CLOSE_LOOP_GO_TO_PICKUP,
    CLOSE_LOOP_COMPLETE_PICKUP,
    CLOSE_LOOP_WAIT,
    CLOSE_LOOP_GO_TO_SHOOT,
    CLOSE_LOOP_COMPLETE_SHOOT,
    BACKROW_LOOP_COMPLETE_PICKUP_1,
    BACKROW_LOOP_COMPLETE_PICKUP_2,
    BACKROW_LOOP_GO_TO_SHOOT,
    BACKROW_LOOP_COMPLETE_SHOOT,
    LEAVE
}
